plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version '3.4.2'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
}

tasks.test {
    useJUnitPlatform()
}

tasks.test {
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
}

application {
    mainClass = 'finance.FinanceApp'
}

run {
    standardInput = System.in

    systemProperties = [
        'file.encoding': 'UTF-8',
        'stdin.encoding': 'UTF-8',
        'stdout.encoding': 'UTF-8',
        'stderr.encoding': 'UTF-8'
    ]

    enableAssertions = true
    ignoreExitValue = true
}